### ISSUE TITLE
Error onload glft file with omi-audio-emitter & Draco extensions

### ISSUE THREAD

**Issue by fiorellasaro** [omigroup/three-omi#8]
Hi!
I have an Issue using a .gltf file with OMI-audio-emitter and Draco extensions:

I cloned this repo to see the example and when I change the reference to my own gltf file (omi-output.gltf):

<img width="797" alt="Captura de Pantalla 2022-03-21 a la(s) 12 17 57" src="https://user-images.githubusercontent.com/39224539/159328355-13b2a462-db85-41b8-a35f-5209d9d6a3dc.png">

omi-output.gltf extensions: 

<img width="691" alt="Captura de Pantalla 2022-03-21 a la(s) 12 14 15" src="https://user-images.githubusercontent.com/39224539/159327658-584fc538-b73e-4f96-9818-69bdd7deb32e.png">

It gives me an error: 

<img width="1434" alt="Captura de Pantalla 2022-03-21 a la(s) 12 11 59" src="https://user-images.githubusercontent.com/39224539/159327359-56fd5895-7b3d-4e2a-af76-f5e3af95d9db.png">

<img width="379" alt="Captura de Pantalla 2022-03-21 a la(s) 12 12 56" src="https://user-images.githubusercontent.com/39224539/159327457-4c3e8ae7-aeb8-4b9e-92cb-418bfabf2b40.png">

Also in package.json

<img width="327" alt="Captura de Pantalla 2022-03-21 a la(s) 12 21 40" src="https://user-images.githubusercontent.com/39224539/159329229-cf4a56e6-faff-43e0-a3ee-103ea97bef1e.png">

These are the only things that I have changed in the repository.

**Comment by antpb** [comment]
Thanks @fiorellasaro !

It doesnt look like you are setting the draco loader in your example. 

If you see the example docs for draco as it relates to gltfloader there is a line 
```
const dracoLoader = new DRACOLoader();
dracoLoader.setDecoderPath( '/examples/js/libs/draco/' );
loader.setDRACOLoader( dracoLoader );
```

I believe that is needed in order for the loader to know what to do with the draco components. I'm not an expert in that extension, but it would make sense the error you are getting without the line to set draco loader. 

Here are the docs I'm looking at: https://threejs.org/docs/#examples/en/loaders/GLTFLoader

**Comment by fiorellasaro** [comment]
> Thanks @fiorellasaro !
> 
> It doesnt look like you are setting the draco loader in your example.
> 
> If you see the example docs for draco as it relates to gltfloader there is a line
> 
> ```
> const dracoLoader = new DRACOLoader();
> dracoLoader.setDecoderPath( '/examples/js/libs/draco/' );
> loader.setDRACOLoader( dracoLoader );
> ```
> 
> I believe that is needed in order for the loader to know what to do with the draco components. I'm not an expert in that extension, but it would make sense the error you are getting without the line to set draco loader.
> 
> Here are the docs I'm looking at: https://threejs.org/docs/#examples/en/loaders/GLTFLoader

Thanks! @antpb 

It seems like is working
but now I have an issue with path inside setDecoderPath:
        
`dracoLoader.setDecoderPath( '/examples/js/libs/draco/' );`

<img width="802" alt="Captura de Pantalla 2022-03-21 a la(s) 14 30 13" src="https://user-images.githubusercontent.com/39224539/159349673-599316ea-bcf6-47cb-a9c7-47e013d177fc.png">

it gives me an error 404 on console:
http://localhost:3000/examples/js/libs/draco/draco_wasm_wrapper.js

<img width="707" alt="Captura de Pantalla 2022-03-21 a la(s) 14 33 21" src="https://user-images.githubusercontent.com/39224539/159350058-a1cd1569-e870-4a26-a132-1e8c9172a5c0.png">


what should be the path?

**Comment by donmccurdy** [comment]
You'll need to host the decoder files (everything except the encoder in [this folder](https://github.com/mrdoob/three.js/tree/dev/examples/js/libs/draco/gltf)) somewhere with your project. Then the correct path would be the path to that folder.

**Comment by robertlong** [comment]
Yup, in this case it can go in a `/examples/public/draco` folder and the path can be `../draco`. This relative path is mostly due to how GitHub Pages is set up.

**Comment by fiorellasaro** [comment]
> You'll need to host the decoder files (everything except the encoder in [this folder](https://github.com/mrdoob/three.js/tree/dev/examples/js/libs/draco/gltf)) somewhere with your project. Then the correct path would be the path to that folder.

@donmccurdy  @robertlong 
Thanks, it works now
